version: "3.9"
services:
  dockerchurn:
    build: .
    ports:
      - "8080:80"
    container_name: dockerchurn-container
  dockerchurn-fe:
    build: ./frontend
    ports:
      - "8081:8081"
    container_name: dockerchurn-container-fe
    environment:
      - HOST=dockerchurn-container
      - PORT=80